In [2]:
import pandas as pd
import numpy as np

In [ ]:
df_barcelona = pd.read_csv("src/sexo_edad.csv")
df_barcelona

,Data_Referencia,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,AEB,Valor,EDAT_1,SEXE
0,2025-01-01,1,Ciutat Vella,1,el Raval,1,6,0,1
1,2025-01-01,1,Ciutat Vella,1,el Raval,1,12,0,2
2,2025-01-01,1,Ciutat Vella,1,el Raval,1,11,1,1
3,2025-01-01,1,Ciutat Vella,1,el Raval,1,8,1,2
4,2025-01-01,1,Ciutat Vella,1,el Raval,1,10,2,1
...,...,...,...,...,...,...,...,...,...
46226,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,..,98,1
46227,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,..,99,1
46228,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,..,99,2
46229,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,6,100,1
46230,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,..,100,2

In [ ]:
df_barcelona['Valor'] = (
    df_barcelona['Valor']
    .str.replace('..','0')        # Quitamos espacios en blanco
)

# Ahora convertimos
df_barcelona['Valor'] = df_barcelona['Valor'].astype(int)

In [73]:
df_barcelona.info()

<class 'pandas.DataFrame'>
RangeIndex: 46231 entries, 0 to 46230
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data_Referencia  46231 non-null  str
 1   Codi_Districte   46231 non-null  int64
 2   Nom_Districte    46231 non-null  str
 3   Codi_Barri       46231 non-null  int64
 4   Nom_Barri        46231 non-null  str
 5   AEB              46231 non-null  int64
 6   Valor            46231 non-null  int64
 7   EDAT_1           46231 non-null  int64
 8   SEXE             46231 non-null  int64
dtypes: int64(6), str(3)
memory usage: 3.2 MB

In [190]:
df_barcelona_18 = df_barcelona[df_barcelona["EDAT_1"] >= 18]
df_barcelona_18

df_barcelona_18["Nom_Districte"] = df_barcelona_18["Nom_Districte"].replace({
    "Sarrià-Sant Gervasi": "Sarrià-St. Gervasi"})

In [191]:
df_barcelona_18

,Data_Referencia,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,AEB,Valor,EDAT_1,SEXE
36,2025-01-01,1,Ciutat Vella,1,el Raval,1,9,18,1
37,2025-01-01,1,Ciutat Vella,1,el Raval,1,10,18,2
38,2025-01-01,1,Ciutat Vella,1,el Raval,1,10,19,1
39,2025-01-01,1,Ciutat Vella,1,el Raval,1,7,19,2
40,2025-01-01,1,Ciutat Vella,1,el Raval,1,12,20,1
...,...,...,...,...,...,...,...,...,...
46226,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,0,98,1
46227,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,0,99,1
46228,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,0,99,2
46229,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,6,100,1
46230,2025-01-01,10,Sant Martí,73,la Verneda i la Pau,233,0,100,2

In [182]:
df_barcelona_18.info()

<class 'pandas.DataFrame'>
Index: 37843 entries, 36 to 46230
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data_Referencia  37843 non-null  str
 1   Codi_Districte   37843 non-null  int64
 2   Nom_Districte    37843 non-null  str
 3   Codi_Barri       37843 non-null  int64
 4   Nom_Barri        37843 non-null  str
 5   AEB              37843 non-null  int64
 6   Valor            37843 non-null  int64
 7   EDAT_1           37843 non-null  int64
 8   SEXE             37843 non-null  int64
dtypes: int64(6), str(3)
memory usage: 2.9 MB

In [ ]:
# Exportar por distrito y barrio

df_barcelona_barris = df_barcelona_18.groupby(['Nom_Districte','Nom_Barri'])['Valor'].sum().reset_index()
df_barcelona_barris
df_barcelona_barris.to_csv("src/result/poblacion.csv")

In [195]:
df_barcelona_barris = df_barcelona_18.groupby(['Nom_Districte'])['Valor'].sum().reset_index()
df_barcelona_barris
df_barcelona_barris.to_csv("src/result/poblacion_distritos.csv")

In [142]:
df_barcelona_distritos = df_barcelona_18.groupby('Nom_Districte')['Valor'].sum().reset_index()
df_barcelona_distritos.describe()

               Valor
count      10.000000
mean   148950.000000
std     52668.022183
min     71736.000000
25%    114439.500000
50%    144235.000000
75%    167385.250000
max    245773.000000

In [171]:
df_renta = pd.read_csv("src/renta.csv")
df_renta

,Any,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Seccio_Censal,Import_Euros
0,2022,1,Ciutat Vella,1,el Raval,1,15940
1,2022,1,Ciutat Vella,1,el Raval,2,13841
2,2022,1,Ciutat Vella,1,el Raval,3,12732
3,2022,1,Ciutat Vella,1,el Raval,4,15749
4,2022,1,Ciutat Vella,1,el Raval,5,13190
...,...,...,...,...,...,...,...
1063,2022,10,Sant Martí,73,la Verneda i la Pau,143,16402
1064,2022,10,Sant Martí,65,el Clot,234,21047
1065,2022,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,235,18576
1066,2022,10,Sant Martí,69,Diagonal Mar i el Front Marítim del Poblenou,236,19369
1067,2022,10,Sant Martí,71,Provençals del Poblenou,237,17676

In [ ]:
df_renta_distrito = df_renta.groupby('Nom_Districte')['Import_Euros']
df_renta_distrito.mean().round(2)

In [197]:
df_renta_distritos = df_renta.groupby(['Nom_Districte', 'Nom_Barri'])['Import_Euros'].mean().round(2)   
df_tipos = df_tipos.rename(columns={"Nombre": "Unidades"})

df_renta_distritos

Nom_Districte       Nom_Barri
Ciutat Vella        Sant Pere, Santa Caterina i la Ribera    19655.15
                    el Barri Gòtic                           18668.11
                    el Raval                                 14221.14
                    la Barceloneta                           17965.91
Eixample            Sant Antoni                              23587.50
                                                               ...
Sarrià-St. Gervasi  Sant Gervasi - la Bonanova               36110.22
                    Sarrià                                   35446.38
                    Vallvidrera, el Tibidabo i les Planes    29594.67
                    el Putxet i el Farró                     29461.42
                    les Tres Torres                          41344.18
Name: Import_Euros, Length: 73, dtype: float64

In [201]:
df_renta_distritos = df_renta.groupby(['Nom_Districte'])['Import_Euros'].mean().round(2)   
df_tipos = df_tipos.rename(columns={"Nombre": "Unidades"})
df_renta_distritos.to_csv("src/result/renta_distritos.csv")
df_renta_distritos

Nom_Districte
Ciutat Vella          17033.31
Eixample              26005.30
Gràcia                25277.75
Horta-Guinardó        20736.37
Les Corts             29393.79
Nou Barris            17093.24
Sant Andreu           20710.93
Sant Martí            21350.67
Sants-Montjuïc        20463.53
Sarrià-St. Gervasi    35155.53
Name: Import_Euros, dtype: float64

In [106]:
df_renta_barrios_mediana = df_renta.groupby('Nom_Barri')['Import_Euros'].median().round(2)
df_renta_barrios_mediana

Nom_Barri
Baró de Viver                    13678.5
Can Baró                         20590.0
Can Peguera                      14582.0
Canyelles                        19957.0
Ciutat Meridiana                 11845.0
                                  ...
la Vila Olímpica del Poblenou    32434.0
la Vila de Gràcia                24564.0
les Corts                        28740.0
les Roquetes                     13630.5
les Tres Torres                  43194.0
Name: Import_Euros, Length: 73, dtype: float64

In [178]:
df_tipos = pd.read_csv("src/propulsion.csv")
df_tipos = df_tipos.rename(columns={"Nombre": "Unidades"})
df_tipos["Tipus_Propulsio"] = df_tipos["Tipus_Propulsio"].replace({
    "Combustió Interna-Gasolina": "Gasolina",
    "Combustió Interna-Gasoil": "Diesel",
    "Elèctrica": "Eléctrica",
    "Híbrid": "Hibrido",
    "Altres": "Otros"
})

In [179]:
df_tipos

,Any,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Seccio_Censal,Tipus_Propulsio,Unidades
0,2024,01,Ciutat Vella,01,el Raval,001,Gasolina,294
1,2024,01,Ciutat Vella,01,el Raval,001,Diesel,249
2,2024,01,Ciutat Vella,01,el Raval,001,Eléctrica,21
3,2024,01,Ciutat Vella,01,el Raval,001,Hibrido,263
4,2024,01,Ciutat Vella,01,el Raval,001,Otros,107
...,...,...,...,...,...,...,...,...
5782,2024,10,Sant Martí,73,la Verneda i la Pau,143,Hibrido,33
5783,2024,10,Sant Martí,73,la Verneda i la Pau,143,Otros,11
5784,2024,NC,No consta,NC,No consta,NC,Gasolina,7
5785,2024,NC,No consta,NC,No consta,NC,Diesel,2
5786,2024,NC,No consta,NC,No consta,NC,Otros,1

In [180]:
df_tipos_distritos = df_tipos.groupby(['Nom_Districte','Nom_Barri', 'Tipus_Propulsio'])['Unidades'].sum().round(2)
df_tipos_distritos

df_tipos_distritos.to_csv("src/result/tipus_vehicle.csv")

In [202]:
df_tipos_distritos = df_tipos.groupby(['Nom_Districte','Tipus_Propulsio'])['Unidades'].sum().round(2)
df_tipos_distritos

df_tipos_distritos.to_csv("src/result/tipus_vehicle_distritos.csv")

In [137]:
df_tipos_barris = df_tipos.groupby(['Nom_Barri', 'Tipus_Propulsio'])['Valor'].sum().round(2)
df_tipos_barris

Nom_Barri        Tipus_Propulsio
Baró de Viver    Diesel              394
                 Gasolina            683
                 Hibrido              36
                 Otros                20
Can Baró         Diesel             1188
                                    ...
les Tres Torres  Eléctrica           306
                 Gasolina           9038
                 Hibrido             841
                 No consta            14
                 Otros                71
Name: Valor, Length: 436, dtype: int64

In [159]:
df_antiguedad = pd.read_csv("src/antiguitat_tipus_vehicle.csv")
df_antiguedad = df_antiguedad.rename(columns={"Nombre": "Valor"})
df_antiguedad_distritos = df_antiguedad.groupby(['Nom_Districte','Nom_Barri', 'Antiguitat'])['Valor'].sum().round(2)
df_antiguedad_distritos.to_csv("src/result/antiguitat_tipus_vehicle.csv")

In [203]:
df_antiguedad = pd.read_csv("src/antiguitat_tipus_vehicle.csv")
df_antiguedad = df_antiguedad.rename(columns={"Nombre": "Valor"})
df_antiguedad_distritos = df_antiguedad.groupby(['Nom_Districte', 'Antiguitat'])['Valor'].sum().round(2)
df_antiguedad_distritos.to_csv("src/result/antiguitat_distritos.csv")

In [160]:
df_antiguedad_distritos

Nom_Districte       Nom_Barri                              Antiguitat
Ciutat Vella        Sant Pere, Santa Caterina i la Ribera  1 any                          1837
                                                           10 anys                         238
                                                           2 anys                         1349
                                                           3 anys                          405
                                                           4 anys                          820
                                                                                          ...
Sarrià-St. Gervasi  les Tres Torres                        9 anys                          534
                                                           D'11 a 20 anys                 3772
                                                           Menys d'un any d'antiguitat     581
                                                           Més de 20 anys                 2402
                                                           No consta                         3
Name: Valor, Length: 994, dtype: int64

In [154]:
df_antiguedad_barrios = df_antiguedad.groupby(['Nom_Barri', 'Antiguitat'])['Valor'].sum().round(2)
df_antiguedad_barrios

df_antiguedad_barrios.to_csv("src/result/antiguitat_tipus_vehicle.csv")

In [5]:
punts = pd.read_csv("src/puntos_carga_barcelona_v2.csv")

punts['cpostal'] = punts['direccion'].str[-4:]
punts['cpostal'] = punts['cpostal'].replace('dral', '8002')

In [7]:
punts['cpostal'] = punts['cpostal'].replace('trum', '8039')

In [8]:
postals = pd.read_csv("src/result/pcode.csv")
postals

postals = postals.rename(columns={"Códigos Postales" : "cpostal"})
punts["cpostal"] = punts["cpostal"].astype(int)

In [10]:
endolls = pd.merge(punts, postals, on='cpostal')
endolls.drop("Unnamed: 0", axis=1, inplace=True)

In [11]:
endolls.head()

,nombre,tipo,direccion,type2,schuko,ccs2,chademo,cpostal,Distrito
0,Ap. BSM - Estació Bcn-Nord,Parking,83 Carrer de Nàpols 08013,88,70,0,0,8013,Eixample
1,Estació Barcelona-Nord,Parking,83 Carrer de Nàpols 08013,58,48,0,0,8013,Eixample
2,Ap. BSM - Rius i Taulet,Parking,17 Avinguda de Rius i Taulet 08004,41,23,0,0,8004,Sants-Montjuïc
3,Rius i Taulet,Parking,17 Avinguda de Rius i Taulet 08004,32,32,0,0,8004,Sants-Montjuïc
4,Ap. BSM - Plaça Bonanova,Parking,2 Plaça de la Bonanova 08022,35,17,0,0,8022,Sarrià-St. Gervasi

In [12]:
columnas_sumar = ['type2', 'schuko', 'ccs2', 'chademo']
endolls['total_punts'] = endolls[columnas_sumar].sum(axis=1)

In [13]:
endolls['total_punts'] = endolls['total_punts'].replace(0, 1)
endolls.head()

,nombre,tipo,direccion,type2,schuko,ccs2,chademo,cpostal,Distrito,total_punts
0,Ap. BSM - Estació Bcn-Nord,Parking,83 Carrer de Nàpols 08013,88,70,0,0,8013,Eixample,158
1,Estació Barcelona-Nord,Parking,83 Carrer de Nàpols 08013,58,48,0,0,8013,Eixample,106
2,Ap. BSM - Rius i Taulet,Parking,17 Avinguda de Rius i Taulet 08004,41,23,0,0,8004,Sants-Montjuïc,64
3,Rius i Taulet,Parking,17 Avinguda de Rius i Taulet 08004,32,32,0,0,8004,Sants-Montjuïc,64
4,Ap. BSM - Plaça Bonanova,Parking,2 Plaça de la Bonanova 08022,35,17,0,0,8022,Sarrià-St. Gervasi,52

In [15]:
endolls = endolls.rename(columns={"Distrito" : "Nom_Districte"})

In [16]:
endolls.to_csv("src/result/endolls.csv")